
services:
  postgres:
    image: postgres:15
    container_name: omnicart_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omnicart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: omnicart_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
